spring:
  application:
    name: sportsDiary
  datasource:
    url: jdbc:postgresql://localhost:5433/my_project
    username: postgres
    password: A123456z
  jpa:
    hibernate:
      ddl-auto: update  # Обновляет схему базы данных, если необходимо
    show-sql: true  # Показывает SQL-запросы в логах
debug: false

springdoc:
  cache:
    disabled: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    url: /api-docs
    disable-swagger-default-url: true
    config-url: /api-docs/swagger-config
